#!/bin/sh

set -e

spruce --version
CURRENT_DIR=$(pwd)
OUTPUT_DIR=${OUTPUT_DIR:-${CURRENT_DIR}/generated-files/}
SPRUCE_SCRIPT_DIR=${SPRUCE_SCRIPT_DIR:-scripts-resource/concourse/tasks/generate_manifest}

SUFFIX=${SUFFIX:-"-tpl.yml"}

for yaml in ${YML_FILES}; do
    if [ ! -e "${yaml}" ]; then
    yaml_dirname=$(dirname "${yaml}")
    mkdir -p "${yaml_dirname}"
    echo "WARNING: ${yaml} does not exist, generating an empty yaml file"
    echo "---" > "${yaml}"
    {
        echo "# This file is automatically generated, you can remove it safely. It may be regenerated"
        echo "{}"
    } >> "${yaml}"
    fi
done
echo "selecting ${SUFFIX} in '${YML_TEMPLATE_DIR}'"
for template in $(ls ${YML_TEMPLATE_DIR}/*${SUFFIX})
do
    filename=$(basename ${template})
    file_extension=${SUFFIX#-tpl}
    echo "processing $filename"
    output_filename=${filename%${SUFFIX}}${file_extension}
    echo "generating ${output_filename}"
    ${SPRUCE_SCRIPT_DIR}/spruce-manifest.sh ${template} ${YML_FILES} >${OUTPUT_DIR}/${output_filename}
done



