resource "local_file" "spec_profile_1" {
  content     = "this file is generated by terraform spec_profile_1 resource !"
  filename = "${path.cwd}/spec-profile-1.txt"
}

# This file is overridden by the one in secrets, otherwise we get an error due to 'my_dummy_var' already define in another spec
variable "my_dummy_var" {
  type = "string"
}