resource "local_file" "spec_profile_2_override" {
  content     = "this file is generated by terraform spec_profile_2-override resource !"
  filename = "${path.cwd}/spec-profile-2-override.txt"
}

# This file is overridden by the one in profile-1, otherwise we get an error due to 'my_dummy_var' already define in another spec
variable "my_dummy_var" {
  type = "string"
}