resource "local_file" "spec_only" {
  content     = "this file is generated by terraform spec_only resource !"
  filename = "${path.cwd}/spec-only.txt"
}


variable "my_dummy_var" {
  type = "string"
}