---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: elpaasoci/cf-cli
    tag: 3b099c3aa806646de2550f13fad8d1ecbdcf45e7
inputs:
  - name: scripts-resource
  - name: template-resource
  - name: credentials-resource
    optional: true
  - name: additional-resource
outputs:
  - name: generated-files
run:
  path: scripts-resource/concourse/tasks/post_deploy/run.sh
params:
  CUSTOM_SCRIPT_DIR:
  SECRETS_DIR: