@startuml
[*] --> bootstrap_all_init_pipelines

state bootstrap_all_init_pipelines {
        init_pipeline: generates and loads using fly cli

 }


init_pipeline --> master_depls_update_generated
init_pipeline --> ops_depls_update_generated
init_pipeline --> xx_depls_update_generated

master_depls_update_generated --> master_depls_generated: loads pipelines specified \n ci-deployment-overview.yml
ops_depls_update_generated --> news_ops_depls_generated: loads
ops_depls_update_generated --> cf_apps_ops_depls_generated: loads
ops_depls_update_generated --> concourse_ops_depls_generated: loads
ops_depls_update_generated --> bosh_ops_depls_generated: loads
ops_depls_update_generated --> bosh_precompile_ops_depls_generated: loads
xx_depls_update_generated --> xx_depls_generated: loads pipelines specified \n ci-deployment-overview.yml

@enduml