@startuml
title
 Bosh usage overview
end title

box "Inception"
	participant Inception
end box
note over Inception
bootstrap
end note

box "Micro-Depls" #LightBlue
	participant "Bosh-Micro" as Micro
    note over Micro
    manage bosh-master
    end note
end box


box "Master-Depls" #LightGreen
    note over Master
        manage ops & expe
    end note
	participant "Bosh-Master" as Master
end box


box "Ops-Depls" #Red
	participant "Bosh-Ops" as Ops
    note over Ops
        mange Cloud Foundry
        and services (p-mysql, memcache, etc...)
    end note
end box

box "Expe-Depls" #LightYellow
	participant "Bosh-Expe" as Expe
    note over Expe
        manage experimentation
    end note
end box


Inception -> Micro: terraform(iaas)
Inception -> Micro: bosh-init(bosh-micro)

Micro -> Master: generate(bosh-master)

Master -> Ops: generate(bosh-ops)
Master -> Expe: generate(bosh-expe)

Ops -> Ops: terraform(CF)



@enduml
